services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory_app_app
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/var
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      APP_SECRET: 1bdd3f8e630e08dbb62b4e1a3e77a414
      DATABASE_URL: "postgresql://app:!ChangeMe!@database:5432/app?serverVersion=16&charset=utf8"
      DATABASE_TEST_URL: "postgresql://app:!ChangeMe!@database:5432/app_test?serverVersion=16&charset=utf8"
      POSTGRES_PASSWORD: "!ChangeMe!"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16-alpine
    container_name: inventory_app_db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: "!ChangeMe!"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
