# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:

services:
  # ---------------------------------------------
  # DEFAULTS
  # ---------------------------------------------
  _defaults:
    autowire: true
    autoconfigure: true

  # ---------------------------------------------
  # BASE APP SERVICES
  # ---------------------------------------------
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # ---------------------------------------------
  # INVENTORY CUSTOM ID â€” PART GENERATORS
  # ---------------------------------------------
  App\Service\CustomId\Part\:
    resource: '../src/Service/CustomId/Part/'
    tags: ['app.inventory_id_part_generator']
